[project]
name = "wnba"
version = "0.1.0"
description = "Scripts to interact with Hello Club - Wellington North Badminton"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icmplib>=3.0.4",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "tabulate>=0.9.0",
]
